import { requireNativeComponent } from 'react-native';

export default {
  logoOmbording: require('../../imgs/LogeOmbording.png'),
  crap: require('./images/crap.jpg'),
  open_box:require('./images/box-open.png'),
  close_box:require('./images/box-close.png'),
  add_product:require('./images/add-product.png'),
  add_product2:require('./images/add_product2.png'),
  add_product3:require('./images/add_product3.png'),
  facebookLoge:require('../../imgs/facebookLoge.png'),
  googleLoge:require('../../imgs/googleLoge.png'),
  backArrow:require('../../imgs/backArrow.png'),
  filterIcon: require('./images/filter-icon.png'),
  priceicon: require('./images/PriceImage.png'),
  dateIcon:require('./images/dateCreated.png'),
  edigIcon: require('./images/editIcon.png'),
  removeIcon: require('./images/removeIcon.png'),
  xico: require('./images/xico.jpg'),
  addUser: require('./images/addUser.png'),
  pending: require('./images/pending.jpeg'),
  settingsIcon: require('./images/settings-icon.png'),
  settingsIconActive: require('./images/settings-active-icon.png'),
  notificationIcon: require('./images/notifications-icon.png'),
  notificationIconActive: require('./images/notifications-active-icon.png'),
  dashboardIcon: require('./images/dashboard-icon.png'),
  dashboardIconActive: require('./images/dashboard-active-icon.png'),
  amigosIcon: require('./images/amigos-icon.png'),
  amigosIconActive: require('./images/amigos-active-icon.png'),
  addIcon: require('./images/add-icon.png'),
  unCheckFriend: require('./images/uncheck-friend-icon.png'),
  checkFriend: require('./images/check-friend-icon.png'),
  mailIcon: require('./images/mail-icon.png'),
  acceptIcon: require('./images/accept-icon.png'),
  rejectIcon: require('./images/reject-icon.png'),
  happyIcon: require('./images/happy-icon.png'),
  showIcon: require('./images/show-icon.png'),
  OneMan: require('./images/personIconx.png'),
  notShowIcon: require('./images/not-show-icon.png'),
  groupIcon: require('./images/GroupPersonsIcon.png'),
  greenGroup: require('./images/green-group-icon.png'),
  GroupIcon: require('./images/login_image_2.png'),
  SiglePerson: require('./images/singlePerson.jpg'),
  arrowDownIcon: require('./images/arrow-down-icon.png'),
  closeIcon: require('./images/close-icon.png'),
  whatsappIcon: require('./images/whatsapp-icon.png'),
  LogoIcon: require('./images/logoalt.png')                   
}
